@echo off
echo Cleaning Next.js cache...
if exist .next rmdir /s /q .next
echo Cleaning node_modules cache...
if exist node_modules rmdir /s /q node_modules
echo Installing dependencies...
npm install
echo Building the application without linting...
npx next build --no-lint
echo Starting the development server...
npm run dev 